### ISSUE TITLE
Question regarding filtering prior to peak calling

### ISSUE THREAD

**Issue by OrangeyO2** [ATpoint/atac_chip_preprocess#18]
Hello @ATpoint , I hope this is a good place for me to ask a question regarding your pipeline.

In some ATAC-seq pipelines, fragments are size filtered (< 100 bp) to select for NFR, then fed into MACS2 for peak calling while some pipelines feed all the fragments.

I was wondering what your rationale was for not selecting for NFR (I tried to go through your source code, and please correct me if I am wrong).

Thanks! (and your help on biostars is always very helpful, thanks so much)

**Comment by ATpoint** [comment]
Hello,

the pipeline uses the 5' ends of each read for peak calling as the ends represent the original transposome insertion events into the genome, meaning that this is where the genome is 'open/accessible'. Accessible to me is not the same as nucleosime-free as also the flanking regions of NFRs produce ATAC-seq signal, and quite a bit of it actually. 

I find using cutsizes a good choice to get peaks. The ends are stored in bed format so that macs2 can easily read them and then extended by 100bp by macs2 to produce some smoothing for peak calling. Here are some relevant chunks:

https://github.com/ATpoint/atac_chip_preprocess/blob/main/main.nf#L304

https://github.com/ATpoint/atac_chip_preprocess/blob/main/modules/cutsites.nf

https://github.com/ATpoint/atac_chip_preprocess/blob/main/main.nf#L91

Filtering for a certain length is possible but it eliminates many reads, thereby reducing detection power. In experiments with great depth and good quality that might be acceptable or not make any difference (I have no benchmark data), but sometimes data are just not great and one really wants all reads to call peaks. 

Hope that helps. 

best,
Alex

**Comment by OrangeyO2** [comment]
Thanks Alex for a thorough reply!

Just one more question, what was the reason for you to use --nomodel --extsize 100 --shift -50 --min-length 250 for macs2 peak calling as opposed to macs2 -f BAMPE? (assuming your pipeline is designed for paired-end data as well)

I am just a little confused with what the consensus (if it even exists) in the field is because Dr. Tao Liu seems to advocate the use of macs2/macs3 -f BAMPE for paired-end ATAC-seq data while quite a lot of papers define their own extsize and shift.

Thanks as always for being super helpful!
